#!/usr/bin/env python3
"""Generate the kernel catalogue of Appendix A from port/agent/kernels.csv.

    python3 book/tools/kernels_tex.py            # writes book/chapters/A-kernels-table.tex
    python3 book/tools/kernels_tex.py --check    # exit 1 if the file is out of date

The table lists every row of kernels.csv whose kernel field names a kernel (K-...), with its route, template,
the WRF 4.6.0 lines it ports (grouped by file) and the plan section; a second table lists the other items of the
kernel table (changes that are not kernels). Rows marked n/a (callers without kernels) are left out.
"""
import csv
import os
import sys
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
CSV = os.path.join(ROOT, 'port', 'agent', 'kernels.csv')
OUT = os.path.join(ROOT, 'book', 'chapters', 'A-kernels-table.tex')


def esc(s):
    """Escape text for LaTeX (ASCII output)."""
    s = s.replace('\u2014', '--').replace('`', '').replace('*', '')
    out = []
    for c in s:
        if c in '_&%#$':
            out.append('\\' + c)
        elif c == '\\':
            out.append('\\textbackslash{}')
        elif c in '{}':
            out.append('\\' + c)
        elif c == '~':
            out.append('\\textasciitilde{}')
        elif c == '^':
            out.append('\\textasciicircum{}')
        elif ord(c) > 127:
            out.append('?')
        else:
            out.append(c)
    return ''.join(out)


def refs(v460):
    """'dir/a.F:10; dir/a.F:20-30; dir/b.F:5' -> 'a.F: 10, 20--30; b.F: 5'."""
    files = OrderedDict()
    for part in v460.split(';'):
        part = part.strip()
        if not part or ':' not in part:
            continue
        path, lines = part.rsplit(':', 1)
        files.setdefault(os.path.basename(path), []).append(lines.replace('-', '--'))
    return '; '.join('\\texttt{%s}: %s' % (brk(esc(f)), ', '.join(ls)) for f, ls in files.items())


def brk(s):
    """Allow line breaks after underscores of an escaped name."""
    return s.replace('\\_', '\\_\\allowbreak{}')


def build():
    with open(CSV, newline='') as fh:
        rows = list(csv.DictReader(fh))
    kern = [r for r in rows if r['kernels'].startswith('K-') and r['status'] != 'n/a']
    other = [r for r in rows if not r['kernels'].startswith('K-') and r['status'] != 'n/a']
    L = []
    L.append('% Generated by book/tools/kernels_tex.py from port/agent/kernels.csv. Do not edit.')
    L.append('\\begingroup\\footnotesize')
    L.append('\\begin{longtable}{p{0.22\\textwidth}p{0.2\\textwidth}cp{0.38\\textwidth}l}')
    L.append('\\caption{The kernels of the port (%d rows).}\\label{tab:kernels}\\\\' % len(kern))
    head = '\\toprule Kernel(s) & Route & T & Lines in WRF 4.6.0 & Plan \\\\ \\midrule'
    L.append(head)
    L.append('\\endfirsthead')
    L.append(head)
    L.append('\\endhead')
    L.append('\\bottomrule')
    L.append('\\endlastfoot')
    for r in kern:
        L.append('%s & \\texttt{%s} & %s & %s & %s \\\\' % (
            esc(r['kernels']).replace('/', '/\\allowbreak{}').replace(', ', ',\\allowbreak{} '),
            brk(esc(r['route'])), esc(r['template']) or '--', refs(r['v460_refs']), esc(r['section'])))
    L.append('\\end{longtable}')
    L.append('')
    L.append('\\begin{longtable}{p{0.22\\textwidth}p{0.2\\textwidth}p{0.38\\textwidth}l}')
    L.append('\\caption{Other items of the kernel table: changes that are not kernels (%d rows).}'
             '\\label{tab:kernel-other}\\\\' % len(other))
    head2 = '\\toprule Item & Route & Lines in WRF 4.6.0 & Plan \\\\ \\midrule'
    L.append(head2)
    L.append('\\endfirsthead')
    L.append(head2)
    L.append('\\endhead')
    L.append('\\bottomrule')
    L.append('\\endlastfoot')
    for r in other:
        L.append('%s & \\texttt{%s} & %s & %s \\\\' % (
            esc(r['kernels']), brk(esc(r['route'])) or '--', refs(r['v460_refs']) or '--', esc(r['section'])))
    L.append('\\end{longtable}')
    L.append('\\endgroup')
    return '\n'.join(L) + '\n'


def main():
    text = build()
    if '--check' in sys.argv[1:]:
        cur = open(OUT).read() if os.path.exists(OUT) else ''
        if cur != text:
            print('kernels_tex: %s is out of date; run python3 book/tools/kernels_tex.py' % OUT)
            return 1
        print('kernels_tex: up to date')
        return 0
    with open(OUT, 'w') as fh:
        fh.write(text)
    print('kernels_tex: wrote %s' % OUT)
    return 0


if __name__ == '__main__':
    sys.exit(main())
