#!/usr/bin/env python3
"""Check that a branch changes only the paths of its area (areas.json, AREAS.md).

  check_area_scope.py <area> [--wp ID] [--base REV] [--head REV | --worktree]
      every changed path must match the area's "owns" patterns (or the shared bookkeeping paths) and none of its
      "never" patterns; roadmap/BACKLOG.md may change only in card status lines; a closed area fails.
      port-wp also runs check_wp_scope.py (routine-level ownership) and needs --wp.
      --base: default the merge base of HEAD and the handoff branch; --head: default HEAD; --worktree: compare the
      working tree (including untracked files) instead of a commit.
  check_area_scope.py --list                 the areas, one per line
  check_area_scope.py --markdown             the table of AREAS.md (generated part)
  check_area_scope.py --check-config         areas.json is valid, AREAS.md is up to date, every backlog card names
                                             an existing area (used by port/gates/static.sh)

LOCKED (AGENTS.md rule 3).
"""
import argparse
import fnmatch
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
CONFIG = os.path.join(REPO, "areas.json")
AREAS_MD = os.path.join(REPO, "AREAS.md")
BACKLOG = os.path.join(REPO, "roadmap", "BACKLOG.md")
BEGIN = "<!-- GENERATED by port/tools/check_area_scope.py --markdown: do not edit below -->"
END = "<!-- END GENERATED -->"
META = re.compile(r"^- \*\*Goal:\*\* .* · \*\*Status:\*\* .*$")
AREA_IN_META = re.compile(r"\*\*Area:\*\* ([a-z0-9-]+)")


def git(*args):
    r = subprocess.run(["git", "-C", REPO] + list(args), capture_output=True, text=True, errors="replace")
    return r.returncode, r.stdout


def load():
    return json.load(open(CONFIG))


def default_base(cfg):
    for ref in ("origin/" + cfg["handoff_branch"], cfg["handoff_branch"]):
        rc, out = git("merge-base", "HEAD", ref)
        if rc == 0 and out.strip():
            return out.strip()
    raise SystemExit("check_area_scope: no handoff branch to start from; pass --base <commit>")


def changed(base, head, worktree):
    if worktree:
        _, out = git("diff", "--name-status", base)
        _, extra = git("ls-files", "--others", "--exclude-standard")
        rows = [l.split("\t") for l in out.splitlines() if l.strip()]
        rows += [["A", f] for f in extra.splitlines() if f.strip()]
    else:
        _, out = git("diff", "--name-status", base, head)
        rows = [l.split("\t") for l in out.splitlines() if l.strip()]
    paths = []
    for r in rows:
        if r[0].startswith("R"):
            paths += [r[1], r[2]]
        else:
            paths.append(r[-1])
    return sorted({p for p in paths if "__pycache__/" not in p and not p.endswith(".pyc")})


def status_only(base, head, worktree, path):
    """True if every changed line of the backlog file is a card's metadata (status) line."""
    args = ["diff", "-U0", base] + ([] if worktree else [head]) + ["--", path]
    _, out = git(*args)
    for l in out.splitlines():
        if l.startswith(("+++", "---", "@@", "diff ", "index ")):
            continue
        if l.startswith(("+", "-")) and not META.match(l[1:]):
            return False
    return True


def match(path, patterns, wp=None):
    for p in patterns:
        if wp:
            p = p.replace("{ID}", wp)
        if fnmatch.fnmatch(path, p):
            return True
    return False


def markdown(cfg):
    rows = ["| Area | Open | Purpose | Entry | Branch | May change |", "|---|---|---|---|---|---|"]
    for a in cfg["areas"]:
        owns = ", ".join("`%s`" % p for p in a["owns"])
        if a.get("never"):
            owns += "; never " + ", ".join("`%s`" % p for p in a["never"])
        rows.append("| `%s` | %s | %s | [%s](%s) | `%s` | %s |" % (
            a["id"], "yes" if a["open"] else "**no**", a["purpose"], a["entry"], a["entry"], a["branch"], owns))
    rows.append("")
    rows.append("Every area may also write its own task log `roadmap/log/<date>-<card>.md` and the status line of its "
                "card in `roadmap/BACKLOG.md`.")
    return "\n".join(rows)


def check_config(cfg):
    bad = []
    ids = [a["id"] for a in cfg["areas"]]
    if len(ids) != len(set(ids)):
        bad.append("duplicate area ids")
    for a in cfg["areas"]:
        for k in ("id", "open", "purpose", "entry", "branch", "who", "owns", "never"):
            if k not in a:
                bad.append("area %s: missing key %s" % (a.get("id"), k))
        if not os.path.exists(os.path.join(REPO, a["entry"])):
            bad.append("area %s: entry %s does not exist" % (a["id"], a["entry"]))
        if a["open"] and not a["owns"]:
            bad.append("area %s: open but owns nothing" % a["id"])
    if not os.path.exists(AREAS_MD):
        bad.append("AREAS.md missing")
    else:
        text = open(AREAS_MD).read()
        if BEGIN not in text or END not in text:
            bad.append("AREAS.md: generated block markers missing")
        else:
            cur = text.split(BEGIN, 1)[1].split(END, 1)[0].strip()
            if cur != markdown(cfg).strip():
                bad.append("AREAS.md: table out of date (python3 port/tools/check_area_scope.py --markdown)")
    if os.path.exists(BACKLOG):
        for n, l in enumerate(open(BACKLOG), 1):
            if l.startswith("- **Goal:**"):
                m = AREA_IN_META.search(l)
                if not m:
                    bad.append("BACKLOG.md line %d: card without an Area" % n)
                elif m.group(1) not in ids:
                    bad.append("BACKLOG.md line %d: unknown area %s" % (n, m.group(1)))
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("area", nargs="?")
    ap.add_argument("--wp")
    ap.add_argument("--base")
    ap.add_argument("--head", default="HEAD")
    ap.add_argument("--worktree", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--markdown", action="store_true")
    ap.add_argument("--check-config", action="store_true")
    a = ap.parse_args()
    cfg = load()
    areas = {x["id"]: x for x in cfg["areas"]}

    if a.list:
        for x in cfg["areas"]:
            print("%-15s %-6s %s" % (x["id"], "open" if x["open"] else "closed", x["entry"]))
        return 0
    if a.markdown:
        print(markdown(cfg))
        return 0
    if a.check_config:
        bad = check_config(cfg)
        for b in bad:
            print("FAIL  " + b)
        print("areas: %s  (%d areas)" % ("PASS" if not bad else "FAIL (%d)" % len(bad), len(areas)))
        return 1 if bad else 0

    if not a.area or a.area not in areas:
        print("check_area_scope: give an area: " + ", ".join(areas), file=sys.stderr)
        return 2
    area = areas[a.area]
    if area.get("routine_scope") and not a.wp:
        print("check_area_scope: area %s needs --wp <ID>" % a.area, file=sys.stderr)
        return 2
    base = a.base or default_base(cfg)
    bad = []
    if not area["open"]:
        bad.append("area %s is closed (%s)" % (a.area, area["purpose"]))
    paths = changed(base, a.head, a.worktree)
    for p in paths:
        if match(p, area["never"], a.wp):
            bad.append("%s: never changed by area %s" % (p, a.area))
        elif match(p, area["owns"], a.wp) or match(p, cfg["shared"]["paths"]):
            continue
        elif p in cfg["shared"]["status_only"]:
            if not status_only(base, a.head, a.worktree, p):
                bad.append("%s: only card status lines may change outside the roadmap area" % p)
        else:
            bad.append("%s: not owned by area %s" % (p, a.area))
    rc_wp = 0
    if area.get("routine_scope"):
        cmd = [sys.executable, os.path.join(HERE, "check_wp_scope.py"), a.wp, "--base", base]
        cmd += ["--worktree"] if a.worktree else ["--head", a.head]
        r = subprocess.run(cmd, capture_output=True, text=True)
        rc_wp = r.returncode
        if rc_wp != 0:
            bad.append("check_wp_scope %s: FAIL\n%s" % (a.wp, (r.stdout + r.stderr).strip()))
    for b in bad:
        print("FAIL  " + b)
    print("check_area_scope %s: %d changed path(s), %s" % (a.area, len(paths), "PASS" if not bad else "FAIL"))
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
