#!/usr/bin/env python3
"""Generate the work-package files of the code-only parallel port, Phases 1-3
(port/agent/CODE_ONLY.md), from port/tools/wp_def.py:

  port/agent/wp/<ID>.md              the card of each work package (locked)
  port/agent/wp/ownership.json       what each work package owns (check_wp_scope.py)
  port/agent/wp/islands/<ID>/*.txt   the island of each routine (gen_island.py output)
  port/agent/WORKPACKAGES.md         the table between the GENERATED markers
and, only if missing (they belong to the work package afterwards):
  port/agent/wp/status/<ID>.md       status file
  port/agent/arith_exceptions.d/<ID>.txt
  WRF/inc/gpu_work_<id>.inc          work-array include (INTERFACES.md I-3)

  gen_wp.py            write everything
  gen_wp.py --check    exit 1 if ownership.json, the WORKPACKAGES.md table or
                       gpu_work_all.inc is out of date, a card, island or
                       per-package file is missing, two work packages own the
                       same thing, a route has no owner, or an open Phase 2/3
                       kernel row is not assigned

The cards and islands quote line numbers of the handoff tree: they are
snapshots (the cards are locked by protect.py), so --check only checks that
they exist; a work package's own edits shift the lines in its files.
"""
import argparse
import csv
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import wp_def  # noqa: E402
import wp_lib  # noqa: E402

REPO = wp_lib.REPO
WPDIR = wp_lib.WPDIR
OUT_OF_SCOPE = {"8.5:o3rad-d02": "nest-forcing data movement (plan.md P5.2); sync point S6 covers it until Phase 5"}
MARK_A = "<!-- GENERATED by port/tools/gen_wp.py: do not edit below -->"
MARK_B = "<!-- END GENERATED -->"


def kernel_rows():
    return list(csv.DictReader(open(os.path.join(wp_lib.AGENT, "kernels.csv"))))


def island_targets(wp, own, routes):
    """[(file, routine, route)] of the routines that get an island"""
    if "islands" in wp:
        out = []
        for name in wp["islands"]:
            if ":" in name:                       # "file:routine@route" (a routine ROUTES.md does not list)
                fpart, rest = name.split(":", 1)
                n, _, r = rest.partition("@")
                out.append((wp_lib.repo_path(fpart), n, r))
                continue
            hit = None
            for r in wp.get("routes", []):
                for f, n, _, _ in routes[r]["routines"]:
                    if n.lower() == name.lower():
                        hit = ("WRF/" + f, n, r)
            if not hit:
                raise SystemExit(f"{wp['id']}: island routine {name} is not a routine of its routes")
            out.append(hit)
        return out
    return [(f, n, r) for f, n, r in own["routines"] if r]


def gen_island(path, routine, route):
    r = subprocess.run([sys.executable, os.path.join(HERE, "gen_island.py"), os.path.join(REPO, path), routine,
                        "--route", "R_" + route.upper()], capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"gen_island.py {path} {routine} failed:\n{r.stdout}{r.stderr}")
    return r.stdout


def card(wp, own, routes, rows, islands):
    L = [f"# {wp['id']} — {wp['title']}", ""]
    L.append(f"Phase {wp['phase']}. Specification: {wp['card']}. Rules: [CODE_ONLY.md](../CODE_ONLY.md), "
             "[CODING_STANDARD.md](../CODING_STANDARD.md), [INTERFACES.md](../INTERFACES.md).")
    L.append(f"Generated by `port/tools/gen_wp.py` from `port/tools/wp_def.py` at the handoff (line numbers of the handoff tree); locked. Your progress goes into "
             f"`{wp_lib.status_file(wp['id'])}`; your branch is `agent/wp/{wp_lib.wp_slug(wp['id'])}`.")
    L += ["", "## You own (nothing else may change on your branch)", ""]
    for f in own["files"]:
        exists = wp_lib.read_lines(f) is not None
        L.append(f"- file `{f}`" + ("" if exists else " (new; create it)"))
    for f, n, r in own["routines"]:
        lines = wp_lib.read_lines(f)
        span = wp_lib.routine_span(lines, n) if lines else None
        base = None
        if r and r in routes:
            for bf, bn, a, b in routes[r]["routines"]:
                if bn.lower() == n.lower():
                    base = (a, b)
        where = f"lines {span[0]}-{span[1]}" if span else "not found"
        if span and base and base[0] != span[0]:
            where += f" (base commit {base[0]}-{base[1]}: KERNEL_REFS.md lines + {span[0] - base[0]})"
        L.append(f"- routine `{n}` in `{f}`, {where}" + (f", route `{r}` (`R_{r.upper()}`)" if r else ""))
    for s in own["specs"]:
        L.append(f"- the module specification part (MODULE .. CONTAINS) of `{s}`")
    for a in own["aux"]:
        L.append(f"- `{a}`")
    L += ["", "Inside an owned routine you may change any line; you may also insert new routines (e.g. module "
          "functions for statement functions, template B) immediately after the END of an owned routine. A change "
          "anywhere else is a scope violation (`check_wp_scope.py`): if you need one, do not make it; write it under "
          "\"Scope requests\" in your status file.", ""]
    keys = [r for r in rows if r["route"] in wp.get("routes", [])]
    if keys:
        L += ["## Kernel rows (port/agent/KERNEL_REFS.md; CPU lines in the CPU-view base commit)", "",
              "| Key | Kernels | Routine(s) | Template | CPU lines (base) | Status at handoff | Notes |",
              "|---|---|---|---|---|---|---|"]
        for r in keys:
            L.append(f"| {r['key']} | {r['kernels']} | {r['routines']} | {r['template']} | "
                     f"{r['base_refs'].replace('; ', '<br>')} | {r['status']} | {r['notes']} |")
        L.append("")
    if wp.get("routes"):
        L += ["## Routes and call sites (port/agent/ROUTES.md)", ""]
        for r in wp["routes"]:
            L.append(f"- `{r}` ({routes[r]['section']}): {routes[r]['raw_defs']} — called from: "
                     f"{routes[r]['calls'].replace('<br>', '; ')}")
        L.append("")
    if islands:
        L += ["## Islands (pre-generated by `port/tools/gen_island.py`, with the call check)", "",
              "Paste each block where its comments say (CODING_STANDARD.md §3). Regenerate with the command in "
              "the file's first line if you can run Python.", ""]
        for f, n, r, path, head in islands:
            L.append(f"- `{path}` — `{n}` ({f}), route `R_{r.upper()}`: {head}")
        L.append("")
    if wp.get("tasks"):
        L += ["## Tasks", ""] + [f"- {t}" for t in wp["tasks"]] + [""]
    if wp.get("notes"):
        L += ["## Notes", ""] + [f"- {t}" for t in wp["notes"]] + [""]
    L += ["## Done (code-only; CODE_ONLY.md §5)", "",
          "- every kernel row above is ported as its template says, or set to `n/a` in your status file with the "
          "reason (e.g. a branch the case never takes);",
          "- every routine with kernels has its island and call check (the files above), and every unported branch "
          "stops under `#ifdef WRF_GPU` with `CALL wrf_error_fatal('<routine>: <option> not ported to the GPU')` "
          "before the entry island;",
          "- the CPU view is unchanged (rule 2), apart from the shared refactors named in Tasks, each in its own "
          "commit titled `Shared refactor: ...`;",
          "- every task above is done or marked blocked with the reason;",
          "- your status file lists each row and task as `coded`, `n/a` or `blocked`, with the commit;",
          "- if you can run Python: `python3 port/tools/check_wp_scope.py " + wp["id"] + "` and "
          "`python3 port/tools/arith_guard.py <your files>` pass.", ""]
    return "\n".join(L)


def status_template(wp, rows):
    L = [f"# {wp['id']} status", "",
         "Written by the work package only (CODE_ONLY.md §6). States: todo, in-progress, coded, n/a, blocked.", "",
         "- State: todo", f"- Branch: agent/wp/{wp_lib.wp_slug(wp['id'])}", "- Last commit:", ""]
    keys = [r for r in rows if r["route"] in wp.get("routes", [])]
    L += ["## Items", "", "| Item | State | Commit | Note |", "|---|---|---|---|"]
    for r in keys:
        st = "n/a" if r["status"] == "n/a" else ("done" if r["status"] == "done" else "todo")
        L.append(f"| {r['key']} | {st} | | {r['notes'] if r['status'] in ('n/a', 'done') else ''} |")
    for i, t in enumerate(wp.get("tasks", []), 1):
        L.append(f"| task {i}: {t[:70]}{'...' if len(t) > 70 else ''} | todo | | |")
    L += ["", "## Scope requests", "", "(changes you need outside \"You own\": file, routine, why; do not make them)",
          "", "## Questions and blockers", "", "## Log", ""]
    return "\n".join(L)


def work_include_template(wp):
    return f"""! Work arrays of work package {wp['id']} (port/agent/INTERFACES.md I-3).
! Included three times by WRF/frame/module_gpu_work.F with GPU_WORK_SECTION set:
!   1  declarations, in the module specification part
!   2  allocation, inside gpu_work_ensure (ni, nj, nk: memory sizes of the
!      largest domain so far; n2d = ni*nj, n3d = ni*nj*nk, n3dp = ni*nj*(nk+1))
!   3  self test, inside gpu_selftest_work
! GPU-only arrays (new temporaries of a GPU kernel) go under #ifdef WRF_GPU in
! all three sections; arrays of a shared refactor (an automatic array of the
! CPU code replaced by a pointer) exist in both builds.  Example:
!
! #if GPU_WORK_SECTION == 1
! #ifdef WRF_GPU
!    REAL, ALLOCATABLE, TARGET, PUBLIC :: work_{wp_lib.wp_slug(wp['id'])}_fqy3(:)
! #endif
! #elif GPU_WORK_SECTION == 2
! #ifdef WRF_GPU
!    CALL gpu_work_alloc_r(work_{wp_lib.wp_slug(wp['id'])}_fqy3, n3d, "work_{wp_lib.wp_slug(wp['id'])}_fqy3")
! #endif
! #elif GPU_WORK_SECTION == 3
! #ifdef WRF_GPU
!    CALL gpu_work_check_r(work_{wp_lib.wp_slug(wp['id'])}_fqy3, "work_{wp_lib.wp_slug(wp['id'])}_fqy3", nwork, nbad)
! #endif
! #endif
!
! Names start with work_{wp_lib.wp_slug(wp['id'])}_ so that no two work packages collide.
! No apostrophes in comments here: cpp reads this file, the WRF sed step does not.
"""


def table(rows_by_wp):
    L = [MARK_A, "", "| ID | Phase | Title | Owns | Kernel rows | Card |", "|---|---|---|---|---|---|"]
    for wp, own, nrows in rows_by_wp:
        owns = len(own["files"]) + len(own["routines"]) + len(own["specs"])
        L.append(f"| {wp['id']} | {wp['phase']} | {wp['title']} | {owns} | {nrows} | [wp/{wp['id']}.md](wp/{wp['id']}.md) |")
    L += ["", "Not assigned (out of scope of Phases 1-3):", ""]
    L += [f"- `{k}`: {v}" for k, v in OUT_OF_SCOPE.items()]
    L += ["", MARK_B]
    return "\n".join(L)


def build():
    own = wp_lib.ownership()
    routes = wp_lib.parse_routes()
    rows = kernel_rows()
    files, problems = {}, []
    problems += wp_lib.collisions(own)
    consts = set(wp_lib.route_constants())
    assigned = {r for wp in wp_def.WPS for r in wp.get("routes", [])}
    for r in routes:
        if r not in consts:
            problems.append(f"route {r} of ROUTES.md has no constant in module_gpu_route.F")
        if routes[r]["section"].startswith(("7", "8")) and r not in assigned:
            problems.append(f"route {r} ({routes[r]['section']}) has no work package")
    for r in rows:
        if r["phase"] in ("2", "3") and r["status"] == "todo" and r["route"] not in assigned \
                and r["key"] not in OUT_OF_SCOPE:
            problems.append(f"kernel row {r['key']} is not assigned to a work package")
    for wid, o in own.items():
        for f, n, _ in o["routines"]:
            lines = wp_lib.read_lines(f)
            if lines is None or not wp_lib.routine_span(lines, n):
                problems.append(f"{wid}: routine {n} not found in {f}")
    summary = []
    owners = {}
    for wp in wp_def.WPS:
        o = own[wp["id"]]
        isl = []
        for f, n, r in island_targets(wp, o, routes):
            text = gen_island(f, n, r)
            rel = f"port/agent/wp/islands/{wp['id']}/{n.lower()}.txt"
            files[rel] = f"! regenerate: python3 port/tools/gen_island.py {f} {n} --route R_{r.upper()}\n" + text
            head = text.split("\n")[1].lstrip("! ").strip() if "\n" in text else ""
            isl.append((f, n, r, rel, head))
        files[f"port/agent/wp/{wp['id']}.md"] = card(wp, o, routes, rows, isl)
        nrows = len([r for r in rows if r["route"] in wp.get("routes", [])])
        summary.append((wp, o, nrows))
        owners[wp["id"]] = dict(phase=wp["phase"], title=wp["title"], branch=f"agent/wp/{wp_lib.wp_slug(wp['id'])}",
                                files=o["files"], aux=o["aux"], specs=o["specs"],
                                routines=[dict(file=f, name=n, route=r) for f, n, r in o["routines"]])
    incs = [wp_lib.work_include(wp) for wp in wp_def.WPS if wp_lib.work_include(wp)]
    files["WRF/inc/gpu_work_all.inc"] = (
        "! Generated by port/tools/gen_wp.py: the work-array include of every work package\n"
        "! (port/agent/INTERFACES.md I-3).  Included by WRF/frame/module_gpu_work.F once per\n"
        "! GPU_WORK_SECTION (1 declarations, 2 allocation, 3 self test).  Do not edit.\n"
        + "".join(f'#include "{os.path.basename(i)}"\n' for i in incs))
    files["port/agent/wp/ownership.json"] = json.dumps(dict(
        comment="generated by port/tools/gen_wp.py from port/tools/wp_def.py; do not edit",
        handoff_branch=wp_lib.HANDOFF_BRANCH, work_packages=owners), indent=1) + "\n"
    wpm = os.path.join(wp_lib.AGENT, "WORKPACKAGES.md")
    text = open(wpm).read() if os.path.exists(wpm) else MARK_A + "\n" + MARK_B + "\n"
    a, b = text.index(MARK_A), text.index(MARK_B) + len(MARK_B)
    files["port/agent/WORKPACKAGES.md"] = text[:a] + table(summary) + text[b:]
    once = {}
    for wp in wp_def.WPS:
        once[wp_lib.status_file(wp["id"])] = status_template(wp, rows)
        once[wp_lib.exceptions_file(wp["id"])] = (
            f"# arith_guard exceptions of {wp['id']} (one per line: <file>|<normalized statement>|<reason>);\n"
            "# the reviewer checks every line (port/tools/arith_guard.py, CODE_ONLY.md).\n")
        if wp_lib.work_include(wp):
            once[wp_lib.work_include(wp)] = work_include_template(wp)
    return files, once, problems


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    files, once, problems = build()
    stale = []
    for rel, text in files.items():
        p = os.path.join(REPO, rel)
        cur = open(p).read() if os.path.exists(p) else None
        snapshot = rel.startswith("port/agent/wp/islands/") or re.match(r"port/agent/wp/[^/]+\.md$", rel)
        if a.check and snapshot and cur is not None:
            continue
        if cur != text:
            stale.append(rel)
            if not a.check:
                os.makedirs(os.path.dirname(p), exist_ok=True)
                open(p, "w").write(text)
    isl_dir = os.path.join(WPDIR, "islands")
    if os.path.isdir(isl_dir):
        for root, _, fs in os.walk(isl_dir):
            for f in fs:
                rel = os.path.relpath(os.path.join(root, f), REPO)
                if rel not in files:
                    stale.append(rel + " (no longer generated)")
                    if not a.check:
                        os.remove(os.path.join(REPO, rel))
    missing = [rel for rel in once if not os.path.exists(os.path.join(REPO, rel))]
    if not a.check:
        for rel in missing:
            p = os.path.join(REPO, rel)
            os.makedirs(os.path.dirname(p), exist_ok=True)
            open(p, "w").write(once[rel])
    for p in problems:
        print("FAIL ", p)
    if a.check:
        for s in stale:
            print("FAIL  out of date:", s, "(run python3 port/tools/gen_wp.py)")
        for m in missing:
            print("FAIL  missing:", m, "(run python3 port/tools/gen_wp.py)")
        ok = not (problems or stale or missing)
        print(f"gen_wp --check: {len(wp_def.WPS)} work packages, {len(files)} generated files: "
              f"{'PASS' if ok else 'FAIL'}")
        return 0 if ok else 1
    print(f"gen_wp: {len(wp_def.WPS)} work packages; {len(stale)} generated files written, {len(missing)} created")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
